### ISSUE TITLE
computeCandidateIndexTables hashing function

### ISSUE THREAD

**Issue by pedro93** [fdintino/xydiff#5]
The hashing function used by computeCandidateIndexTables returns the same value for a buffer where the less significant 4 bytes are different, this leads to an equal match based solely on https://github.com/fdintino/xydiff/blob/master/src/Diff_NodesManager.cpp#L362.

To log this event, I modified the function to this:

``` cpp
void NodesManager::computeCandidateIndexTables(int v0nodeID) {
    class AtomicInfo & myAtomicInfo = v0node[ v0nodeID ] ;

    listOfCandidatesByParentLevelByHash[0][myAtomicInfo.mySubtreeHash.value].v0node.push_back(myAtomicInfo.myID);

    int relativeLevel=1;
    int relativeId=myAtomicInfo.myParent;
    while((relativeLevel<=MIN_CANDIDATEPARENT_LEVEL)&&(relativeId>0)) {
        unsigned long buf[2];
        buf[1]=relativeId;
        buf[0]=myAtomicInfo.mySubtreeHash.value;
        hash32 tablekey((unsigned char*)buf, 8);
        indexToCandidates &theIndex = listOfCandidatesByParentLevelByHash[relativeLevel]; 
        theIndex[tablekey.value].v0node.push_back(myAtomicInfo.myID);
        std::cout << "computeCandidateIndexTables components for hashing: " << relativeId << " and " << myAtomicInfo.mySubtreeHash.value << " result: " <<tablekey.value<< std::endl;
        relativeLevel++;
        relativeId=v0node[relativeId].myParent;
    }
    int childID = myAtomicInfo.firstChild ;
    while(childID) {
        computeCandidateIndexTables( childID );
        childID = v0node[childID].nextSibling ;
    }
}
```

The output is this:

``` bash
computeCandidateIndexTables components for hashing: 5 and 11388135541494718721 result: 4822318754194940015
computeCandidateIndexTables components for hashing: 28 and 11388135541494718721 result: 4822318754194940015
```

For 2 different nodes, with the same mySubtreeHash.value but different relativeId have the same hashed value. Is this intended? Further into the algorithm in the getBestCandidate function potential matches are missed.

**Comment by fdintino** [comment]
I'm thinking this might be due to different platforms having different sizes for `unsigned long`. What do you get if you log:

``` cpp
std::cout << "Size of unsigned long: " << sizeof(unsigned long) << std::endl;
```

If it outputs a number greater than 4 then that's the source of the issue. In which case the fix would be to change

``` cpp
hash32 tablekey((unsigned char*)buf, 8);
```

to

``` cpp
hash32 tablekey((unsigned char*)buf, 2 * sizeof(unsigned long));
```

**Comment by pedro93** [comment]
It is now working, this function could perhaps be reworked to work in a cross-platform manner using pre-processor directives. You may close this issue
